name: Docker container workflow

on:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: [self-hosted, docker]
    container:
      image: ubuntu:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: print hostname
        run: hostname


